// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBin14pkL9Vm6OkfU1yrBaPP6-tDpWHs-g',
    appId: '1:424579899799:web:80d89242ee2eea098964d2',  // Temporary - add proper web app to Firebase Console
    messagingSenderId: '424579899799',
    projectId: 'recsy-e2ae5',
    authDomain: 'recsy-e2ae5.firebaseapp.com',
    databaseURL: 'https://recsy-e2ae5.firebaseio.com',
    storageBucket: 'recsy-e2ae5.firebasestorage.app',
    measurementId: 'G-QLHTWLE9YJ',  // Temporary - get real one from Firebase Console
  );

//   const firebaseConfig = { // For RecsyWeb
//   apiKey: "AIzaSyBin14pkL9Vm6OkfU1yrBaPP6-tDpWHs-g",
//   authDomain: "recsy-e2ae5.firebaseapp.com",
//   databaseURL: "https://recsy-e2ae5.firebaseio.com",
//   projectId: "recsy-e2ae5",
//   storageBucket: "recsy-e2ae5.firebasestorage.app",
//   messagingSenderId: "424579899799",
//   appId: "1:424579899799:web:80d89242ee2eea098964d2",
//   measurementId: "G-QLHTWLE9YJ"
// };

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuzImvD2tMRDIBpmZpFMl8dvKop01qJ74',
    appId: '1:424579899799:android:d64c52c439468d438964d2',
    messagingSenderId: '424579899799',
    projectId: 'recsy-e2ae5',
    databaseURL: 'https://recsy-e2ae5.firebaseio.com',
    storageBucket: 'recsy-e2ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.mobileRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: 'your-macos-client-id',
    iosBundleId: 'com.example.mobileRecommender',
  );
}