$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "Airflow cannot run natively on Windows because it imports POSIX-only modules like fcntl."
Write-Host "Use Docker, WSL Ubuntu, Linux, or macOS for the local standalone fallback."
Write-Host ""
Write-Host "Recommended WSL path from PowerShell:"
Write-Host ""
Write-Host "  wsl --install -d Ubuntu"
Write-Host "  wsl -d Ubuntu"
Write-Host ""
Write-Host "Then inside Ubuntu:"
Write-Host ""
Write-Host "  cd /mnt/c/Users/rohan/Documents/RECSY/mobile_recommender/orchestration/airflow"
Write-Host "  chmod +x ./local-standalone.sh"
Write-Host "  ./local-standalone.sh"
Write-Host ""
Write-Host "If Ubuntu is already installed, skip the install step and run:"
Write-Host ""
Write-Host "  wsl -d Ubuntu"
Write-Host ""
exit 1
