/**
 * Starter corpus — 20 phones spanning budget → flagship, 2024 → early 2026
 * launches, across six global-English brands.
 *
 * Purpose: seed enough variety for the retrieval + recommender pipelines to
 * exercise realistic filter paths (budget, foldable, compact, camera-focused,
 * gaming). Spec values are best-effort at seed time; Phase 2 ingestion
 * overwrites numeric fields with reviewer-sourced values where they appear.
 *
 * To add a phone: append an entry below, keep `slug` kebab-case and unique,
 * and make sure `spec_json` parses via `PhoneSpecSchema`.
 */
import { PhoneSpecSchema, type PhoneSpec } from '@/features/phones/schema';

export interface PhoneSeed {
  slug: string;
  brand: string;
  model: string;
  variant?: string;
  tagline: string;
  launchDate: string; // ISO YYYY-MM-DD
  msrpUsd: string; // numeric string to preserve precision
  status: 'active' | 'discontinued' | 'upcoming';
  regionAvailability: string[];
  /** Optional product photo (Wikimedia Commons or other allowlisted CDN). */
  imageUrl?: string;
  specJson: PhoneSpec;
}

const P = (spec: unknown): PhoneSpec => PhoneSpecSchema.parse(spec);

export const PHONE_SEEDS: readonly PhoneSeed[] = [
  // ---------------------------------------------------------------------------
  // Flagship tier ($900+)
  // ---------------------------------------------------------------------------
  {
    slug: 'apple-iphone-16-pro-max',
    brand: 'Apple',
    model: 'iPhone 16 Pro Max',
    tagline: 'The largest-screened iPhone 16, tuned for video and zoom.',
    launchDate: '2024-09-20',
    msrpUsd: '1199.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'AU', 'CA', 'JP'],
    specJson: P({
      display: {
        size_in: 6.9,
        resolution: '2868x1320',
        refresh_rate_hz: 120,
        panel_type: 'LTPO Super Retina XDR OLED',
        peak_brightness_nits: 2000,
        features: ['LTPO', 'Always-on', 'ProMotion'],
      },
      chipset: 'Apple A18 Pro',
      process_nm: 3,
      ram_gb: 8,
      storage_options_gb: [256, 512, 1024],
      rear_cameras: [
        { type: 'main', mp: 48, aperture_f: 1.78, ois: true },
        { type: 'ultrawide', mp: 48, aperture_f: 2.2 },
        { type: 'telephoto', mp: 12, aperture_f: 2.8, zoom: '5x optical', ois: true },
      ],
      front_camera: { mp: 12, aperture_f: 1.9 },
      battery_mah: 4685,
      charging: { wired_w: 27, wireless_w: 25 },
      weight_g: 227,
      os: 'iOS 18',
      update_policy: '6+ years of iOS updates',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.3', nfc: true, usb: 'USB-C 3.1' },
      ip_rating: 'IP68',
      colors: ['Black Titanium', 'White Titanium', 'Desert Titanium', 'Natural Titanium'],
      foldable: false,
      highlights: ['top-tier video', 'long battery', 'best-in-class ecosystem'],
    }),
  },
  {
    slug: 'apple-iphone-16-pro',
    brand: 'Apple',
    model: 'iPhone 16 Pro',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Camera_of_iPhone_16_Pro.jpg',
    tagline: 'Flagship iPhone performance in a one-hand-friendly size.',
    launchDate: '2024-09-20',
    msrpUsd: '999.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'AU', 'CA', 'JP'],
    specJson: P({
      display: {
        size_in: 6.3,
        resolution: '2622x1206',
        refresh_rate_hz: 120,
        panel_type: 'LTPO Super Retina XDR OLED',
        peak_brightness_nits: 2000,
        features: ['LTPO', 'Always-on', 'ProMotion'],
      },
      chipset: 'Apple A18 Pro',
      process_nm: 3,
      ram_gb: 8,
      storage_options_gb: [128, 256, 512, 1024],
      rear_cameras: [
        { type: 'main', mp: 48, aperture_f: 1.78, ois: true },
        { type: 'ultrawide', mp: 48, aperture_f: 2.2 },
        { type: 'telephoto', mp: 12, aperture_f: 2.8, zoom: '5x optical', ois: true },
      ],
      front_camera: { mp: 12, aperture_f: 1.9 },
      battery_mah: 3582,
      charging: { wired_w: 27, wireless_w: 25 },
      weight_g: 199,
      os: 'iOS 18',
      update_policy: '6+ years of iOS updates',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.3', nfc: true, usb: 'USB-C 3.1' },
      ip_rating: 'IP68',
      colors: ['Black Titanium', 'White Titanium', 'Desert Titanium', 'Natural Titanium'],
      foldable: false,
      highlights: ['compact flagship', 'excellent cameras', 'long software support'],
    }),
  },
  {
    slug: 'samsung-galaxy-s25-ultra',
    brand: 'Samsung',
    model: 'Galaxy S25 Ultra',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Samsung_Galaxy_S25_Ultra.jpg',
    tagline: 'Productivity-first Android flagship with S Pen.',
    launchDate: '2025-02-07',
    msrpUsd: '1299.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'AU', 'CA', 'JP', 'KR'],
    specJson: P({
      display: {
        size_in: 6.9,
        resolution: '3120x1440',
        refresh_rate_hz: 120,
        panel_type: 'Dynamic AMOLED 2X LTPO',
        peak_brightness_nits: 2600,
        features: ['LTPO', 'Always-on', 'Corning Gorilla Armor 2'],
      },
      chipset: 'Qualcomm Snapdragon 8 Elite for Galaxy',
      process_nm: 3,
      ram_gb: 12,
      storage_options_gb: [256, 512, 1024],
      rear_cameras: [
        { type: 'main', mp: 200, aperture_f: 1.7, ois: true },
        { type: 'ultrawide', mp: 50, aperture_f: 1.9 },
        { type: 'telephoto', mp: 10, aperture_f: 2.4, zoom: '3x optical', ois: true },
        { type: 'periscope', mp: 50, aperture_f: 3.4, zoom: '5x optical', ois: true },
      ],
      front_camera: { mp: 12, aperture_f: 2.2 },
      battery_mah: 5000,
      charging: { wired_w: 45, wireless_w: 15, reverse_wireless_w: 4.5 },
      weight_g: 218,
      os: 'Android 15 with One UI 7',
      update_policy: '7 years of OS + security',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.4', nfc: true, usb: 'USB-C 3.2' },
      ip_rating: 'IP68',
      colors: ['Titanium Silverblue', 'Titanium Black', 'Titanium Whitesilver', 'Titanium Gray'],
      foldable: false,
      highlights: ['S Pen productivity', 'class-leading zoom', '200MP main sensor'],
    }),
  },
  {
    slug: 'samsung-galaxy-s25-plus',
    brand: 'Samsung',
    model: 'Galaxy S25+',
    tagline: 'Flagship Samsung without the Ultra tax.',
    launchDate: '2025-02-07',
    msrpUsd: '999.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'AU', 'CA', 'JP', 'KR'],
    specJson: P({
      display: {
        size_in: 6.7,
        resolution: '3120x1440',
        refresh_rate_hz: 120,
        panel_type: 'Dynamic AMOLED 2X LTPO',
        peak_brightness_nits: 2600,
        features: ['LTPO', 'Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 8 Elite for Galaxy',
      process_nm: 3,
      ram_gb: 12,
      storage_options_gb: [256, 512],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.8, ois: true },
        { type: 'ultrawide', mp: 12, aperture_f: 2.2 },
        { type: 'telephoto', mp: 10, aperture_f: 2.4, zoom: '3x optical', ois: true },
      ],
      front_camera: { mp: 12, aperture_f: 2.2 },
      battery_mah: 4900,
      charging: { wired_w: 45, wireless_w: 15, reverse_wireless_w: 4.5 },
      weight_g: 190,
      os: 'Android 15 with One UI 7',
      update_policy: '7 years of OS + security',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.4', nfc: true, usb: 'USB-C 3.2' },
      ip_rating: 'IP68',
      colors: ['Icyblue', 'Navy', 'Mint', 'Silver Shadow'],
      foldable: false,
      highlights: ['big-screen flagship', '7-year updates', 'balanced camera'],
    }),
  },
  {
    slug: 'google-pixel-9-pro-xl',
    brand: 'Google',
    model: 'Pixel 9 Pro XL',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/e/e5/Google_Pixel_9_Pro_XL_%28back%29.jpg',
    tagline: 'Google\u2019s largest Pro with AI-first software.',
    launchDate: '2024-08-22',
    msrpUsd: '1099.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'EU', 'AU', 'CA', 'JP'],
    specJson: P({
      display: {
        size_in: 6.8,
        resolution: '2992x1344',
        refresh_rate_hz: 120,
        panel_type: 'LTPO OLED',
        peak_brightness_nits: 3000,
        features: ['LTPO', 'Always-on'],
      },
      chipset: 'Google Tensor G4',
      process_nm: 4,
      ram_gb: 16,
      storage_options_gb: [128, 256, 512, 1024],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.68, ois: true },
        { type: 'ultrawide', mp: 48, aperture_f: 1.7 },
        { type: 'telephoto', mp: 48, aperture_f: 2.8, zoom: '5x optical', ois: true },
      ],
      front_camera: { mp: 42, aperture_f: 2.2 },
      battery_mah: 5060,
      charging: { wired_w: 37, wireless_w: 23, reverse_wireless_w: 5 },
      weight_g: 221,
      os: 'Android 14',
      update_policy: '7 years of OS + security (Pixel promise)',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.3', nfc: true, usb: 'USB-C 3.2' },
      ip_rating: 'IP68',
      colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
      foldable: false,
      highlights: ['AI features', 'night photography', '7-year updates'],
    }),
  },
  {
    slug: 'google-pixel-9-pro',
    brand: 'Google',
    model: 'Pixel 9 Pro',
    tagline: 'The compact Pro Pixel, no XL compromises on cameras.',
    launchDate: '2024-08-22',
    msrpUsd: '999.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'EU', 'AU', 'CA', 'JP'],
    specJson: P({
      display: {
        size_in: 6.3,
        resolution: '2856x1280',
        refresh_rate_hz: 120,
        panel_type: 'LTPO OLED',
        peak_brightness_nits: 3000,
        features: ['LTPO', 'Always-on'],
      },
      chipset: 'Google Tensor G4',
      process_nm: 4,
      ram_gb: 16,
      storage_options_gb: [128, 256, 512, 1024],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.68, ois: true },
        { type: 'ultrawide', mp: 48, aperture_f: 1.7 },
        { type: 'telephoto', mp: 48, aperture_f: 2.8, zoom: '5x optical', ois: true },
      ],
      front_camera: { mp: 42, aperture_f: 2.2 },
      battery_mah: 4700,
      charging: { wired_w: 27, wireless_w: 21, reverse_wireless_w: 5 },
      weight_g: 199,
      os: 'Android 14',
      update_policy: '7 years of OS + security (Pixel promise)',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.3', nfc: true, usb: 'USB-C 3.2' },
      ip_rating: 'IP68',
      colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
      foldable: false,
      highlights: ['pocketable Pro', 'AI features', 'best-in-class image processing'],
    }),
  },
  {
    slug: 'oneplus-13',
    brand: 'OnePlus',
    model: '13',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/13/OnePlus_13_volume_slider.jpg',
    tagline: 'Performance-first flagship with massive battery.',
    launchDate: '2025-01-07',
    msrpUsd: '899.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'CN'],
    specJson: P({
      display: {
        size_in: 6.82,
        resolution: '3168x1440',
        refresh_rate_hz: 120,
        panel_type: 'LTPO AMOLED',
        peak_brightness_nits: 4500,
        features: ['LTPO', 'Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 8 Elite',
      process_nm: 3,
      ram_gb: 16,
      storage_options_gb: [256, 512, 1024],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.6, ois: true },
        { type: 'ultrawide', mp: 50, aperture_f: 2.0 },
        { type: 'telephoto', mp: 50, aperture_f: 2.6, zoom: '3x optical', ois: true },
      ],
      front_camera: { mp: 32, aperture_f: 2.4 },
      battery_mah: 6000,
      charging: { wired_w: 100, wireless_w: 50, reverse_wireless_w: 10 },
      weight_g: 213,
      os: 'Android 15 with OxygenOS 15',
      update_policy: '4 years OS + 6 years security',
      connectivity: {
        wifi: 'Wi-Fi 7',
        bluetooth: '5.4',
        nfc: true,
        ir_blaster: true,
        usb: 'USB-C 3.2',
      },
      ip_rating: 'IP68/IP69',
      colors: ['Arctic Dawn', 'Black Eclipse', 'Midnight Ocean'],
      foldable: false,
      highlights: ['huge battery', 'fastest charging', 'gaming-friendly'],
    }),
  },
  {
    slug: 'xiaomi-14-ultra',
    brand: 'Xiaomi',
    model: '14 Ultra',
    tagline: 'Leica partnership, variable-aperture main camera.',
    launchDate: '2024-02-25',
    msrpUsd: '1499.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU', 'CN'],
    specJson: P({
      display: {
        size_in: 6.73,
        resolution: '3200x1440',
        refresh_rate_hz: 120,
        panel_type: 'LTPO AMOLED',
        peak_brightness_nits: 3000,
        features: ['LTPO', 'Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 8 Gen 3',
      process_nm: 4,
      ram_gb: 16,
      storage_options_gb: [512, 1024],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.63, ois: true, sensor_size: '1.0-inch' },
        { type: 'ultrawide', mp: 50, aperture_f: 1.8 },
        { type: 'telephoto', mp: 50, aperture_f: 1.8, zoom: '3.2x optical', ois: true },
        { type: 'periscope', mp: 50, aperture_f: 2.5, zoom: '5x optical', ois: true },
      ],
      front_camera: { mp: 32, aperture_f: 2.0 },
      battery_mah: 5300,
      charging: { wired_w: 90, wireless_w: 80, reverse_wireless_w: 10 },
      weight_g: 219,
      os: 'Android 14 with HyperOS',
      update_policy: '4 years OS + 5 years security',
      connectivity: {
        wifi: 'Wi-Fi 7',
        bluetooth: '5.4',
        nfc: true,
        ir_blaster: true,
        usb: 'USB-C 3.2',
      },
      ip_rating: 'IP68',
      colors: ['Black', 'White', 'Blue'],
      foldable: false,
      highlights: ['1-inch camera sensor', 'Leica tuning', 'photography-focused'],
    }),
  },
  // ---------------------------------------------------------------------------
  // Premium tier ($600–$900)
  // ---------------------------------------------------------------------------
  {
    slug: 'apple-iphone-16',
    brand: 'Apple',
    model: 'iPhone 16',
    tagline: 'The iPhone for most people.',
    launchDate: '2024-09-20',
    msrpUsd: '799.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'AU', 'CA', 'JP'],
    specJson: P({
      display: {
        size_in: 6.1,
        resolution: '2556x1179',
        refresh_rate_hz: 60,
        panel_type: 'Super Retina XDR OLED',
        peak_brightness_nits: 2000,
        features: [],
      },
      chipset: 'Apple A18',
      process_nm: 3,
      ram_gb: 8,
      storage_options_gb: [128, 256, 512],
      rear_cameras: [
        { type: 'main', mp: 48, aperture_f: 1.6, ois: true },
        { type: 'ultrawide', mp: 12, aperture_f: 2.2 },
      ],
      front_camera: { mp: 12, aperture_f: 1.9 },
      battery_mah: 3561,
      charging: { wired_w: 20, wireless_w: 25 },
      weight_g: 170,
      os: 'iOS 18',
      update_policy: '6+ years of iOS updates',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.3', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP68',
      colors: ['Black', 'White', 'Pink', 'Teal', 'Ultramarine'],
      foldable: false,
      highlights: ['balanced pick', 'Apple Intelligence ready', 'best resale'],
    }),
  },
  {
    slug: 'samsung-galaxy-s25',
    brand: 'Samsung',
    model: 'Galaxy S25',
    tagline: 'Compact Galaxy flagship with 7-year update promise.',
    launchDate: '2025-02-07',
    msrpUsd: '799.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'AU', 'CA', 'JP', 'KR'],
    specJson: P({
      display: {
        size_in: 6.2,
        resolution: '2340x1080',
        refresh_rate_hz: 120,
        panel_type: 'Dynamic AMOLED 2X LTPO',
        peak_brightness_nits: 2600,
        features: ['LTPO'],
      },
      chipset: 'Qualcomm Snapdragon 8 Elite for Galaxy',
      process_nm: 3,
      ram_gb: 12,
      storage_options_gb: [128, 256, 512],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.8, ois: true },
        { type: 'ultrawide', mp: 12, aperture_f: 2.2 },
        { type: 'telephoto', mp: 10, aperture_f: 2.4, zoom: '3x optical', ois: true },
      ],
      front_camera: { mp: 12, aperture_f: 2.2 },
      battery_mah: 4000,
      charging: { wired_w: 25, wireless_w: 15, reverse_wireless_w: 4.5 },
      weight_g: 162,
      os: 'Android 15 with One UI 7',
      update_policy: '7 years of OS + security',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.4', nfc: true, usb: 'USB-C 3.2' },
      ip_rating: 'IP68',
      colors: ['Icyblue', 'Navy', 'Mint', 'Silver Shadow'],
      foldable: false,
      highlights: ['compact', 'flagship chipset', '7-year support'],
    }),
  },
  {
    slug: 'google-pixel-9',
    brand: 'Google',
    model: 'Pixel 9',
    tagline: 'Clean Pixel AI experience without the Pro price.',
    launchDate: '2024-08-22',
    msrpUsd: '799.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'EU', 'AU', 'CA', 'JP'],
    specJson: P({
      display: {
        size_in: 6.3,
        resolution: '2424x1080',
        refresh_rate_hz: 120,
        panel_type: 'OLED',
        peak_brightness_nits: 2700,
        features: [],
      },
      chipset: 'Google Tensor G4',
      process_nm: 4,
      ram_gb: 12,
      storage_options_gb: [128, 256],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.68, ois: true },
        { type: 'ultrawide', mp: 48, aperture_f: 1.7 },
      ],
      front_camera: { mp: 10.5, aperture_f: 2.2 },
      battery_mah: 4700,
      charging: { wired_w: 27, wireless_w: 15 },
      weight_g: 198,
      os: 'Android 14',
      update_policy: '7 years of OS + security (Pixel promise)',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.3', nfc: true, usb: 'USB-C 3.2' },
      ip_rating: 'IP68',
      colors: ['Obsidian', 'Porcelain', 'Wintergreen', 'Peony'],
      foldable: false,
      highlights: ['AI features', 'simple & clean', '7-year updates'],
    }),
  },
  {
    slug: 'nothing-phone-2a-plus',
    brand: 'Nothing',
    model: 'Phone (2a) Plus',
    tagline: 'Design-first mid-flagship with Glyph interface.',
    launchDate: '2024-07-31',
    msrpUsd: '449.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU'],
    specJson: P({
      display: {
        size_in: 6.7,
        resolution: '2412x1084',
        refresh_rate_hz: 120,
        panel_type: 'LTPS AMOLED',
        peak_brightness_nits: 1300,
        features: ['Always-on'],
      },
      chipset: 'MediaTek Dimensity 7350 Pro',
      process_nm: 4,
      ram_gb: 12,
      storage_options_gb: [256, 512],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.88, ois: true },
        { type: 'ultrawide', mp: 50, aperture_f: 2.2 },
      ],
      front_camera: { mp: 50, aperture_f: 2.2 },
      battery_mah: 5000,
      charging: { wired_w: 50, wireless_w: 0 },
      weight_g: 190,
      os: 'Android 14 with Nothing OS 2.6',
      update_policy: '3 years OS + 4 years security',
      connectivity: { wifi: 'Wi-Fi 6', bluetooth: '5.3', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP54',
      colors: ['Black', 'White', 'Grey'],
      foldable: false,
      highlights: ['distinctive design', 'Glyph interface', 'clean software'],
    }),
  },
  // ---------------------------------------------------------------------------
  // Mid tier ($350–$600)
  // ---------------------------------------------------------------------------
  {
    slug: 'google-pixel-9a',
    brand: 'Google',
    model: 'Pixel 9a',
    tagline: 'Pixel AI at half the flagship price.',
    launchDate: '2025-04-10',
    msrpUsd: '499.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'EU', 'AU', 'CA', 'JP', 'IN'],
    specJson: P({
      display: {
        size_in: 6.3,
        resolution: '2424x1080',
        refresh_rate_hz: 120,
        panel_type: 'OLED',
        peak_brightness_nits: 2700,
        features: [],
      },
      chipset: 'Google Tensor G4',
      process_nm: 4,
      ram_gb: 8,
      storage_options_gb: [128, 256],
      rear_cameras: [
        { type: 'main', mp: 48, aperture_f: 1.7, ois: true },
        { type: 'ultrawide', mp: 13, aperture_f: 2.2 },
      ],
      front_camera: { mp: 13, aperture_f: 2.2 },
      battery_mah: 5100,
      charging: { wired_w: 23, wireless_w: 7.5 },
      weight_g: 185.9,
      os: 'Android 15',
      update_policy: '7 years of OS + security (Pixel promise)',
      connectivity: { wifi: 'Wi-Fi 6E', bluetooth: '5.3', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP68',
      colors: ['Obsidian', 'Porcelain', 'Peony', 'Iris'],
      foldable: false,
      highlights: ['best value camera', 'flagship chipset', '7-year updates'],
    }),
  },
  {
    slug: 'samsung-galaxy-a55-5g',
    brand: 'Samsung',
    model: 'Galaxy A55 5G',
    tagline: 'Mid-range with flagship-adjacent software support.',
    launchDate: '2024-03-11',
    msrpUsd: '449.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU', 'AU'],
    specJson: P({
      display: {
        size_in: 6.6,
        resolution: '2340x1080',
        refresh_rate_hz: 120,
        panel_type: 'Super AMOLED',
        peak_brightness_nits: 1000,
        features: ['Always-on'],
      },
      chipset: 'Samsung Exynos 1480',
      process_nm: 4,
      ram_gb: 8,
      storage_options_gb: [128, 256],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.8, ois: true },
        { type: 'ultrawide', mp: 12, aperture_f: 2.2 },
        { type: 'macro', mp: 5, aperture_f: 2.4 },
      ],
      front_camera: { mp: 32, aperture_f: 2.2 },
      battery_mah: 5000,
      charging: { wired_w: 25, wireless_w: 0 },
      weight_g: 213,
      os: 'Android 14 with One UI 6.1',
      update_policy: '4 years OS + 5 years security',
      connectivity: { wifi: 'Wi-Fi 6', bluetooth: '5.3', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP67',
      colors: ['Awesome Navy', 'Awesome Iceblue', 'Awesome Lilac', 'Awesome Lemon'],
      foldable: false,
      highlights: ['long updates for the price', 'solid AMOLED', 'stereo speakers'],
    }),
  },
  {
    slug: 'oneplus-nord-4',
    brand: 'OnePlus',
    model: 'Nord 4',
    tagline: 'Metal-body mid-ranger with flagship charging speed.',
    launchDate: '2024-07-16',
    msrpUsd: '499.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU'],
    specJson: P({
      display: {
        size_in: 6.74,
        resolution: '2772x1240',
        refresh_rate_hz: 120,
        panel_type: 'AMOLED',
        peak_brightness_nits: 2150,
        features: ['Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 7+ Gen 3',
      process_nm: 4,
      ram_gb: 12,
      storage_options_gb: [256, 512],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.8, ois: true },
        { type: 'ultrawide', mp: 8, aperture_f: 2.2 },
      ],
      front_camera: { mp: 16, aperture_f: 2.4 },
      battery_mah: 5500,
      charging: { wired_w: 100, wireless_w: 0 },
      weight_g: 199.5,
      os: 'Android 14 with OxygenOS 14',
      update_policy: '4 years OS + 6 years security',
      connectivity: { wifi: 'Wi-Fi 6', bluetooth: '5.4', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP65',
      colors: ['Mercurial Silver', 'Oasis Green', 'Obsidian Midnight'],
      foldable: false,
      highlights: ['metal build', '100W charging', 'fluid software'],
    }),
  },
  {
    slug: 'nothing-phone-3a-pro',
    brand: 'Nothing',
    model: 'Phone (3a) Pro',
    tagline: 'Periscope zoom in a mid-range body.',
    launchDate: '2025-03-04',
    msrpUsd: '459.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU'],
    specJson: P({
      display: {
        size_in: 6.77,
        resolution: '2392x1080',
        refresh_rate_hz: 120,
        panel_type: 'LTPS AMOLED',
        peak_brightness_nits: 3000,
        features: ['Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 7s Gen 3',
      process_nm: 4,
      ram_gb: 12,
      storage_options_gb: [256],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.88, ois: true },
        { type: 'periscope', mp: 50, aperture_f: 2.55, zoom: '3x optical', ois: true },
        { type: 'ultrawide', mp: 8, aperture_f: 2.2 },
      ],
      front_camera: { mp: 50, aperture_f: 2.2 },
      battery_mah: 5000,
      charging: { wired_w: 50, wireless_w: 0 },
      weight_g: 211,
      os: 'Android 15 with Nothing OS 3.1',
      update_policy: '3 years OS + 6 years security',
      connectivity: { wifi: 'Wi-Fi 6', bluetooth: '5.4', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP64',
      colors: ['Black', 'Grey', 'Blue'],
      foldable: false,
      highlights: ['periscope zoom under $500', 'Glyph interface', 'solid performance'],
    }),
  },
  // ---------------------------------------------------------------------------
  // Budget tier (<$350)
  // ---------------------------------------------------------------------------
  {
    slug: 'samsung-galaxy-a35-5g',
    brand: 'Samsung',
    model: 'Galaxy A35 5G',
    tagline: 'Samsung software support at a budget price.',
    launchDate: '2024-03-11',
    msrpUsd: '399.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU', 'AU'],
    specJson: P({
      display: {
        size_in: 6.6,
        resolution: '2340x1080',
        refresh_rate_hz: 120,
        panel_type: 'Super AMOLED',
        peak_brightness_nits: 1000,
        features: ['Always-on'],
      },
      chipset: 'Samsung Exynos 1380',
      process_nm: 5,
      ram_gb: 8,
      storage_options_gb: [128, 256],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.8, ois: true },
        { type: 'ultrawide', mp: 8, aperture_f: 2.2 },
        { type: 'macro', mp: 5, aperture_f: 2.4 },
      ],
      front_camera: { mp: 13, aperture_f: 2.2 },
      battery_mah: 5000,
      charging: { wired_w: 25, wireless_w: 0 },
      weight_g: 209,
      os: 'Android 14 with One UI 6.1',
      update_policy: '4 years OS + 5 years security',
      connectivity: { wifi: 'Wi-Fi 5', bluetooth: '5.3', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP67',
      colors: ['Awesome Navy', 'Awesome Iceblue', 'Awesome Lilac', 'Awesome Lemon'],
      foldable: false,
      highlights: ['class-leading update policy', 'AMOLED on budget', 'IP67 rare at this price'],
    }),
  },
  {
    slug: 'motorola-edge-50-fusion',
    brand: 'Motorola',
    model: 'Edge 50 Fusion',
    tagline: 'Light, fast-charging budget with curved OLED.',
    launchDate: '2024-04-16',
    msrpUsd: '299.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU', 'AU'],
    specJson: P({
      display: {
        size_in: 6.7,
        resolution: '2400x1080',
        refresh_rate_hz: 144,
        panel_type: 'pOLED',
        peak_brightness_nits: 1600,
        features: ['Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 7s Gen 2',
      process_nm: 4,
      ram_gb: 8,
      storage_options_gb: [128, 256],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.8, ois: true },
        { type: 'ultrawide', mp: 13, aperture_f: 2.2 },
      ],
      front_camera: { mp: 32, aperture_f: 2.4 },
      battery_mah: 5000,
      charging: { wired_w: 68, wireless_w: 15 },
      weight_g: 174.9,
      os: 'Android 14 with Hello UX',
      update_policy: '3 years OS + 4 years security',
      connectivity: { wifi: 'Wi-Fi 6', bluetooth: '5.3', nfc: true, usb: 'USB-C 2.0' },
      ip_rating: 'IP68',
      colors: ['Forest Blue', 'Hot Pink', 'Marshmallow Blue'],
      foldable: false,
      highlights: ['light & thin', 'curved OLED at the price', '68W charging'],
    }),
  },
  {
    slug: 'xiaomi-redmi-note-14-pro-plus',
    brand: 'Xiaomi',
    model: 'Redmi Note 14 Pro+',
    tagline: 'Spec-heavy budget pick with Leica-tuned cameras.',
    launchDate: '2024-12-09',
    msrpUsd: '329.00',
    status: 'active',
    regionAvailability: ['GB', 'IN', 'EU', 'CN'],
    specJson: P({
      display: {
        size_in: 6.67,
        resolution: '2712x1220',
        refresh_rate_hz: 120,
        panel_type: 'AMOLED',
        peak_brightness_nits: 3000,
        features: ['Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 7s Gen 3',
      process_nm: 4,
      ram_gb: 12,
      storage_options_gb: [256, 512],
      rear_cameras: [
        { type: 'main', mp: 200, aperture_f: 1.68, ois: true },
        { type: 'ultrawide', mp: 8, aperture_f: 2.2 },
        { type: 'macro', mp: 2, aperture_f: 2.4 },
      ],
      front_camera: { mp: 20, aperture_f: 2.2 },
      battery_mah: 5110,
      charging: { wired_w: 120, wireless_w: 0 },
      weight_g: 210.8,
      os: 'Android 14 with HyperOS',
      update_policy: '3 years OS + 4 years security',
      connectivity: {
        wifi: 'Wi-Fi 6',
        bluetooth: '5.4',
        nfc: true,
        ir_blaster: true,
        usb: 'USB-C 2.0',
      },
      ip_rating: 'IP68',
      colors: ['Midnight Black', 'Lavender Purple', 'Phantom White', 'Coral Green'],
      foldable: false,
      highlights: ['200MP sensor', '120W charging', 'IP68 rare for price'],
    }),
  },
  // ---------------------------------------------------------------------------
  // Foldable
  // ---------------------------------------------------------------------------
  {
    slug: 'samsung-galaxy-z-fold-6',
    brand: 'Samsung',
    model: 'Galaxy Z Fold6',
    tagline: 'Folding productivity with S Pen and refined hinge.',
    launchDate: '2024-07-24',
    msrpUsd: '1899.00',
    status: 'active',
    regionAvailability: ['US', 'GB', 'IN', 'EU', 'AU', 'CA', 'JP', 'KR'],
    specJson: P({
      display: {
        size_in: 7.6,
        resolution: '2160x1856',
        refresh_rate_hz: 120,
        panel_type: 'Dynamic AMOLED 2X LTPO',
        peak_brightness_nits: 2600,
        features: ['LTPO', 'Always-on'],
      },
      chipset: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy',
      process_nm: 4,
      ram_gb: 12,
      storage_options_gb: [256, 512, 1024],
      rear_cameras: [
        { type: 'main', mp: 50, aperture_f: 1.8, ois: true },
        { type: 'ultrawide', mp: 12, aperture_f: 2.2 },
        { type: 'telephoto', mp: 10, aperture_f: 2.4, zoom: '3x optical', ois: true },
      ],
      front_camera: { mp: 10, aperture_f: 2.2 },
      battery_mah: 4400,
      charging: { wired_w: 25, wireless_w: 15, reverse_wireless_w: 4.5 },
      weight_g: 239,
      os: 'Android 14 with One UI 6.1.1',
      update_policy: '7 years of OS + security',
      connectivity: { wifi: 'Wi-Fi 7', bluetooth: '5.3', nfc: true, usb: 'USB-C 3.2' },
      ip_rating: 'IPX8',
      colors: ['Silver Shadow', 'Pink', 'Navy', 'Crafted Black'],
      foldable: true,
      highlights: ['foldable productivity', 'S Pen support', '7-year updates'],
    }),
  },
] as const;

if (PHONE_SEEDS.length !== 20) {
  // Intentional compile-time-ish guard: the smoke test also verifies this.

  console.warn(`[seed] expected 20 phones, got ${PHONE_SEEDS.length}`);
}
